# https://github.com/JoaoVitorBernardino/keycloak-docker-compose
# https://www.keycloak.org/server/containers

version: '3'
services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.0.5
    command: start-dev
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: '${KC_DB_URL_HOST}'
      KC_DB_URL_DATABASE: '${KC_DB_URL_DATABASE}'
      KC_DB_PASSWORD: '${KC_DB_PASSWORD}'
      KC_DB_USERNAME: '${KC_DB_USERNAME}'
      KEYCLOAK_ADMIN: '${KEYCLOAK_ADMIN}'
      KEYCLOAK_ADMIN_PASSWORD: '${KEYCLOAK_ADMIN_PASSWORD}'
    ports:
      - 8081:8080
    networks:
      - keycloak-network
networks:
  keycloak-network:
    external: true